version: '3'
services:
  zookeeperService:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeperService
    ports:
      - '2181:2181'
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes